mobile_number = input("Enter your mobile number")
"""booking.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCi9qLz6bNqk-HzdggZ2H3dnKelKlYir
"""

def movie_booking():
  print("---Movie Ticket Booking Sytem---")

  user_name = input("Enter your name:")

  ticket_type =input("Enter ticket type(Regular/VIP):").strip().lower()

  if ticket_type == "regular":
    price_per_ticket = 500
  elif ticket_type == "vip":
    price_per_ticket = 1000
  else:
    print("Invalid ticket type entered.")
    return

  try:
    num_tickets = int(input("Enter number of tickets"))
    if num_tickets <= 0:
      raise ValueError
  except ValueError:
      print("Please enter a valid number of tickets.")
      return

  total_cost = price_per_ticket * num_tickets

  discount = 0
  if total_cost > 3000:
    discount = total_cost * 0.10

  Final_amount = total_cost - discount

  print(f"\n--- Receipt for {user_name}---")
  print(f"Ticket Type: {ticket_type.capitalize()}")
  print(f"Number of Tickets: {num_tickets}")
  print(f"Total Cost: {total_cost}")
  print(f"Discount: {discount}")
  print(f"Final Amount to pay: {final_amount}")
